// Comprehensive International Country Database with Visual Flags & Calling Codes for VortexChat

export const COUNTRIES = [
  // Top Featured Countries (Explicitly Requested & High-Traffic)
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', flagUrl: 'https://flagcdn.com/w80/bd.png', format: '1XXX-XXXXXX' },
  { code: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳', flagUrl: 'https://flagcdn.com/w80/in.png', format: 'XXXXX-XXXXX' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷', flagUrl: 'https://flagcdn.com/w80/ar.png', format: '9 11 XXXX-XXXX' },
  { code: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸', flagUrl: 'https://flagcdn.com/w80/us.png', format: '(XXX) XXX-XXXX' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧', flagUrl: 'https://flagcdn.com/w80/gb.png', format: 'XXXX XXXXXX' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', flagUrl: 'https://flagcdn.com/w80/sa.png', format: '5X XXX XXXX' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪', flagUrl: 'https://flagcdn.com/w80/ae.png', format: '5X XXX XXXX' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', flagUrl: 'https://flagcdn.com/w80/pk.png', format: '3XX XXXXXXX' },

  // Global Alphabetical Countries (100+ Total Coverage)
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', flagUrl: 'https://flagcdn.com/w80/af.png', format: '7X XXX XXXX' },
  { code: 'AL', name: 'Albania', dialCode: '+355', flag: '🇦🇱', flagUrl: 'https://flagcdn.com/w80/al.png', format: '6X XXX XXXX' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: '🇩🇿', flagUrl: 'https://flagcdn.com/w80/dz.png', format: '5XX XX XX XX' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', flag: '🇦🇲', flagUrl: 'https://flagcdn.com/w80/am.png', format: 'XX XXXXXX' },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺', flagUrl: 'https://flagcdn.com/w80/au.png', format: '4XX XXX XXX' },
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹', flagUrl: 'https://flagcdn.com/w80/at.png', format: '6XX XXXXXXX' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿', flagUrl: 'https://flagcdn.com/w80/az.png', format: '5X XXX XX XX' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', flagUrl: 'https://flagcdn.com/w80/bh.png', format: '3XXX XXXX' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪', flagUrl: 'https://flagcdn.com/w80/be.png', format: '4XX XX XX XX' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹', flagUrl: 'https://flagcdn.com/w80/bt.png', format: '17 XXX XXX' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: '🇧🇴', flagUrl: 'https://flagcdn.com/w80/bo.png', format: '7XXX XXXX' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷', flagUrl: 'https://flagcdn.com/w80/br.png', format: '(XX) 9XXXX-XXXX' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', flagUrl: 'https://flagcdn.com/w80/bn.png', format: '7XX XXXX' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬', flagUrl: 'https://flagcdn.com/w80/bg.png', format: '8X XXX XXXX' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: '🇰🇭', flagUrl: 'https://flagcdn.com/w80/kh.png', format: '1X XXX XXX' },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', flagUrl: 'https://flagcdn.com/w80/ca.png', format: '(XXX) XXX-XXXX' },
  { code: 'CL', name: 'Chile', dialCode: '+56', flag: '🇨🇱', flagUrl: 'https://flagcdn.com/w80/cl.png', format: '9 XXXX XXXX' },
  { code: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳', flagUrl: 'https://flagcdn.com/w80/cn.png', format: '1XX XXXX XXXX' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', flag: '🇨🇴', flagUrl: 'https://flagcdn.com/w80/co.png', format: '3XX XXX XXXX' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', flagUrl: 'https://flagcdn.com/w80/cr.png', format: '8XXX XXXX' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', flag: '🇭🇷', flagUrl: 'https://flagcdn.com/w80/hr.png', format: '9X XXX XXXX' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: '🇨🇾', flagUrl: 'https://flagcdn.com/w80/cy.png', format: '9X XXXXXX' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿', flagUrl: 'https://flagcdn.com/w80/cz.png', format: '7XX XXX XXX' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰', flagUrl: 'https://flagcdn.com/w80/dk.png', format: 'XX XX XX XX' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1809', flag: '🇩🇴', flagUrl: 'https://flagcdn.com/w80/do.png', format: '809-XXX-XXXX' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: '🇪🇨', flagUrl: 'https://flagcdn.com/w80/ec.png', format: '9X XXX XXXX' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', flagUrl: 'https://flagcdn.com/w80/eg.png', format: '1X XXXX XXXX' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', flagUrl: 'https://flagcdn.com/w80/et.png', format: '9X XXX XXXX' },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮', flagUrl: 'https://flagcdn.com/w80/fi.png', format: '4X XXX XXXX' },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', flagUrl: 'https://flagcdn.com/w80/fr.png', format: '6 XX XX XX XX' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', flag: '🇬🇪', flagUrl: 'https://flagcdn.com/w80/ge.png', format: '5XX XXX XXX' },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪', flagUrl: 'https://flagcdn.com/w80/de.png', format: '1XX XXXXXXXX' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', flagUrl: 'https://flagcdn.com/w80/gh.png', format: '2X XXX XXXX' },
  { code: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷', flagUrl: 'https://flagcdn.com/w80/gr.png', format: '69X XXX XXXX' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', flagUrl: 'https://flagcdn.com/w80/hk.png', format: '9XXX XXXX' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', flag: '🇭🇺', flagUrl: 'https://flagcdn.com/w80/hu.png', format: '20 XXX XXXX' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', flag: '🇮🇸', flagUrl: 'https://flagcdn.com/w80/is.png', format: '6XX XXXX' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', flagUrl: 'https://flagcdn.com/w80/id.png', format: '8XX-XXXX-XXXX' },
  { code: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', flagUrl: 'https://flagcdn.com/w80/ir.png', format: '9XX XXX XXXX' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: '🇮🇶', flagUrl: 'https://flagcdn.com/w80/iq.png', format: '7XX XXX XXXX' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪', flagUrl: 'https://flagcdn.com/w80/ie.png', format: '8X XXX XXXX' },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱', flagUrl: 'https://flagcdn.com/w80/il.png', format: '5X-XXX-XXXX' },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹', flagUrl: 'https://flagcdn.com/w80/it.png', format: '3XX XXX XXXX' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲', flagUrl: 'https://flagcdn.com/w80/jm.png', format: '876-XXX-XXXX' },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵', flagUrl: 'https://flagcdn.com/w80/jp.png', format: 'XX-XXXX-XXXX' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', flag: '🇯🇴', flagUrl: 'https://flagcdn.com/w80/jo.png', format: '7 XXXX XXXX' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿', flagUrl: 'https://flagcdn.com/w80/kz.png', format: '7XX XXX-XX-XX' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', flagUrl: 'https://flagcdn.com/w80/ke.png', format: '7XX XXXXXX' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷', flagUrl: 'https://flagcdn.com/w80/kr.png', format: '10-XXXX-XXXX' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', flagUrl: 'https://flagcdn.com/w80/kw.png', format: 'XXXX XXXX' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: '🇱🇧', flagUrl: 'https://flagcdn.com/w80/lb.png', format: '7X XXX XXX' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', flagUrl: 'https://flagcdn.com/w80/lu.png', format: '6XX XX XX XX' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', flagUrl: 'https://flagcdn.com/w80/my.png', format: '1X-XXX XXXX' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', flagUrl: 'https://flagcdn.com/w80/mv.png', format: '7XX XXXX' },
  { code: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹', flagUrl: 'https://flagcdn.com/w80/mt.png', format: '9XXX XXXX' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽', flagUrl: 'https://flagcdn.com/w80/mx.png', format: 'XX XXXX XXXX' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: '🇲🇳', flagUrl: 'https://flagcdn.com/w80/mn.png', format: '8X XX XXXX' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', flag: '🇲🇦', flagUrl: 'https://flagcdn.com/w80/ma.png', format: '6XX-XXXXXX' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', flagUrl: 'https://flagcdn.com/w80/mm.png', format: '9 XXXX XXXX' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵', flagUrl: 'https://flagcdn.com/w80/np.png', format: '98XXXXXXXX' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱', flagUrl: 'https://flagcdn.com/w80/nl.png', format: '6 XXXXXXXX' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', flagUrl: 'https://flagcdn.com/w80/nz.png', format: '2X XXX XXXX' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', flagUrl: 'https://flagcdn.com/w80/ng.png', format: '8XX XXX XXXX' },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴', flagUrl: 'https://flagcdn.com/w80/no.png', format: '4XX XX XXX' },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', flagUrl: 'https://flagcdn.com/w80/om.png', format: '9XXX XXXX' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸', flagUrl: 'https://flagcdn.com/w80/ps.png', format: '59 XXX XXXX' },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', flagUrl: 'https://flagcdn.com/w80/pa.png', format: '6XXX XXXX' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', flagUrl: 'https://flagcdn.com/w80/py.png', format: '9XX XXX XXX' },
  { code: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪', flagUrl: 'https://flagcdn.com/w80/pe.png', format: '9XX XXX XXX' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', flagUrl: 'https://flagcdn.com/w80/ph.png', format: '9XX XXX XXXX' },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱', flagUrl: 'https://flagcdn.com/w80/pl.png', format: 'XXX XXX XXX' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', flagUrl: 'https://flagcdn.com/w80/pt.png', format: '9X XXX XXXX' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', flagUrl: 'https://flagcdn.com/w80/qa.png', format: 'XXXX XXXX' },
  { code: 'RO', name: 'Romania', dialCode: '+40', flag: '🇷🇴', flagUrl: 'https://flagcdn.com/w80/ro.png', format: '7XX XXX XXX' },
  { code: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺', flagUrl: 'https://flagcdn.com/w80/ru.png', format: '9XX XXX-XX-XX' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', flag: '🇷🇸', flagUrl: 'https://flagcdn.com/w80/rs.png', format: '6X XXX XXXX' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', flagUrl: 'https://flagcdn.com/w80/sg.png', format: '8XXX XXXX' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: '🇸🇰', flagUrl: 'https://flagcdn.com/w80/sk.png', format: '9XX XXX XXX' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦', flagUrl: 'https://flagcdn.com/w80/za.png', format: '7X XXX XXXX' },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸', flagUrl: 'https://flagcdn.com/w80/es.png', format: '6XX XX XX XX' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', flagUrl: 'https://flagcdn.com/w80/lk.png', format: '7X XXX XXXX' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪', flagUrl: 'https://flagcdn.com/w80/se.png', format: '7X XXX XX XX' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭', flagUrl: 'https://flagcdn.com/w80/ch.png', format: '7X XXX XX XX' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: '🇹🇼', flagUrl: 'https://flagcdn.com/w80/tw.png', format: '9XX XXX XXX' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: '🇹🇿', flagUrl: 'https://flagcdn.com/w80/tz.png', format: '7XX XXX XXX' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭', flagUrl: 'https://flagcdn.com/w80/th.png', format: '8X XXX XXXX' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹', flagUrl: 'https://flagcdn.com/w80/tt.png', format: '868-XXX-XXXX' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: '🇹🇳', flagUrl: 'https://flagcdn.com/w80/tn.png', format: 'XX XXX XXX' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷', flagUrl: 'https://flagcdn.com/w80/tr.png', format: '5XX XXX XX XX' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬', flagUrl: 'https://flagcdn.com/w80/ug.png', format: '7XX XXXXXX' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', flagUrl: 'https://flagcdn.com/w80/ua.png', format: 'XX XXX XX XX' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', flagUrl: 'https://flagcdn.com/w80/uy.png', format: '9X XXX XXX' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿', flagUrl: 'https://flagcdn.com/w80/uz.png', format: '9X XXX XX XX' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', flagUrl: 'https://flagcdn.com/w80/ve.png', format: '4XX-XXX-XXXX' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', flagUrl: 'https://flagcdn.com/w80/vn.png', format: '9X XXX XXXX' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪', flagUrl: 'https://flagcdn.com/w80/ye.png', format: '7XX XXX XXX' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', flagUrl: 'https://flagcdn.com/w80/zw.png', format: '7X XXX XXXX' },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Bangladesh (🇧🇩 +880) as default
