// VortexChat - Bandwidth & Resolution Tiers
// Specially engineered for extreme data saving & real-time telemetry

export const AUDIO_ONLY_TIER = {
  id: 'audio_only',
  name: 'Crystal Clear Audio',
  shortLabel: 'Audio Only',
  resolution: 'None',
  fps: 0,
  audioCodec: 'Opus (8-12 kbps)',
  videoCodec: 'Disabled',
  bitrateKbps: 80, // nominal with packet overhead
  videoBitrateKbps: 0,
  audioBitrateKbps: 12,
  estimatedMbPerMin: 0.6, // Exactly ~0.6 MB/min as requested
  dataTag: 'ULTRA ECO',
  tagColor: '#00E676',
  badgeBg: 'rgba(0, 230, 118, 0.15)',
  description: 'Pure Opus voice compression with minimal packet overhead. Saves 96% data.',
  recommendedFor: 'Poor 2G/3G or limited prepaid cellular data plans',
  savingsVsNormal: '96%',
};

export const RESOLUTION_TIERS = [
  {
    id: '360p',
    name: '360p Ultra Data Saver',
    shortLabel: '360p',
    resolution: '640 x 360',
    fps: 20,
    audioCodec: 'Opus 12kbps',
    videoCodec: 'AV1 / H.264 Low-Complexity',
    videoBitrateKbps: 140,
    audioBitrateKbps: 12,
    bitrateKbps: 152,
    estimatedMbPerMin: 1.15, // ~1.2 MB/min
    dataTag: 'ULTRA SAVER',
    tagColor: '#00F2FE',
    badgeBg: 'rgba(0, 242, 254, 0.15)',
    description: 'Drastically reduced bandwidth while preserving face visibility and clarity.',
    recommendedFor: '2G/3G networks, low data packages, weak roaming signals',
    savingsVsNormal: '82%',
    batteryImpact: 'Very Low',
  },
  {
    id: '480p',
    name: '480p Eco Saver',
    shortLabel: '480p',
    resolution: '854 x 480',
    fps: 24,
    audioCodec: 'Opus 16kbps',
    videoCodec: 'H.264 Baseline Profile',
    videoBitrateKbps: 340,
    audioBitrateKbps: 16,
    bitrateKbps: 356,
    estimatedMbPerMin: 2.67, // ~2.7 MB/min
    dataTag: 'ECO SAVER',
    tagColor: '#38EF7D',
    badgeBg: 'rgba(56, 239, 125, 0.15)',
    description: 'Optimal balance of readable mobile video with sharp data conservation.',
    recommendedFor: 'Standard 4G LTE with data limits, commuting, roaming',
    savingsVsNormal: '60%',
    batteryImpact: 'Low',
  },
  {
    id: '720p',
    name: '720p Balanced HD',
    shortLabel: '720p',
    resolution: '1280 x 720',
    fps: 30,
    audioCodec: 'Opus 24kbps',
    videoCodec: 'VP9 / H.264 Main',
    videoBitrateKbps: 800,
    audioBitrateKbps: 24,
    bitrateKbps: 824,
    estimatedMbPerMin: 6.18, // ~6.2 MB/min
    dataTag: 'BALANCED HD',
    tagColor: '#7F00FF',
    badgeBg: 'rgba(127, 0, 255, 0.15)',
    description: 'High definition streaming for clear group calls and desktop presentations.',
    recommendedFor: 'Stable Wi-Fi or unlimited 4G/5G connections',
    savingsVsNormal: '0% (Standard Benchmark)',
    batteryImpact: 'Medium',
  },
  {
    id: '1080p',
    name: '1080p Full High Definition',
    shortLabel: '1080p',
    resolution: '1920 x 1080',
    fps: 30,
    audioCodec: 'Opus 32kbps Wideband',
    videoCodec: 'VP9 / H.265 High Profile',
    videoBitrateKbps: 1800,
    audioBitrateKbps: 32,
    bitrateKbps: 1832,
    estimatedMbPerMin: 13.74, // ~13.7 MB/min
    dataTag: 'HIGH DEF',
    tagColor: '#FF007A',
    badgeBg: 'rgba(255, 0, 122, 0.15)',
    description: 'Studio crystal clear quality. Noticeable data consumption.',
    recommendedFor: 'High-speed broadband Wi-Fi, studio podcasts',
    savingsVsNormal: '-120%',
    batteryImpact: 'High',
  },
  {
    id: '4k',
    name: '4K Ultra Stream',
    shortLabel: '4K UHD',
    resolution: '3840 x 2160',
    fps: 30,
    audioCodec: 'Opus 48kbps Hi-Fi',
    videoCodec: 'AV1 / HEVC Ultra',
    videoBitrateKbps: 6400,
    audioBitrateKbps: 48,
    bitrateKbps: 6448,
    estimatedMbPerMin: 48.36, // ~48.4 MB/min
    dataTag: 'ULTRA HIGH',
    tagColor: '#FFB300',
    badgeBg: 'rgba(255, 179, 0, 0.15)',
    description: 'Maximal resolution for professional broadcasts. Warning: consumes massive data!',
    recommendedFor: 'Fiber optic connections & unlimited Wi-Fi only',
    savingsVsNormal: '-680%',
    batteryImpact: 'Maximum',
  },
];

export const SCREEN_SHARE_MODES = [
  {
    id: 'ultra_hd',
    name: 'Ultra-Sharp 60 FPS',
    fps: 60,
    resolution: '1920 x 1080 (60 FPS Ultra HD)',
    bitrateKbps: 2200,
    estimatedMbPerMin: 16.5,
    badge: 'CRYSTAL SHARP 60FPS',
    description: 'Crisp 60 FPS broadcast with subpixel text clarity. Ideal for live coding, documents & games.',
  },
  {
    id: 'fluid_motion',
    name: 'Smooth Motion (1080p)',
    fps: 30,
    resolution: '1920 x 1080 (30 FPS Full HD)',
    bitrateKbps: 950,
    estimatedMbPerMin: 7.1,
    badge: 'SMOOTH FULL HD',
    description: 'Smooth frame-rate for animations, app demonstrations, and video presentations.',
  },
  {
    id: 'standard_demo',
    name: 'Balanced HD (720p)',
    fps: 30,
    resolution: '1280 x 720 (30 FPS HD)',
    bitrateKbps: 450,
    estimatedMbPerMin: 3.3,
    badge: 'BALANCED HD',
    description: 'Balanced bandwidth for regular screen walkthroughs on mobile data.',
  },
  {
    id: 'eco_slides',
    name: 'Eco Slide Share (5 FPS)',
    fps: 5,
    resolution: '1280 x 720 (Downsampled to 5 FPS)',
    bitrateKbps: 90,
    estimatedMbPerMin: 0.68,
    badge: '85% DATA SAVER',
    description: 'Ultra-low frame rate optimized for documents, code review, slides and PDFs.',
  },
];

export const NETWORK_CONDITIONS = [
  { id: '2g', label: 'Edge / 2G', speed: '64 kbps', recommendedTier: 'audio_only', qualityColor: '#FF3366' },
  { id: '3g', label: '3G Mobile', speed: '384 kbps', recommendedTier: '360p', qualityColor: '#FFB300' },
  { id: '4g', label: '4G LTE', speed: '2.5 Mbps', recommendedTier: '480p', qualityColor: '#38EF7D' },
  { id: 'wifi', label: 'Fast Wi-Fi', speed: '25 Mbps', recommendedTier: '720p', qualityColor: '#00F2FE' },
];
